### ISSUE TITLE
[Bug] Styled Records

### ISSUE THREAD

**Issue by stunslave** [surftimer/SurfTimer-discord#13]
Style stage records announce into Map Records and not Stage records.

![image](https://user-images.githubusercontent.com/47533535/150674013-43e46021-911c-402d-b4a3-74f3b8d017a1.png)

**Comment by tslashd** [comment]
Style records should get sent to styled webhook if i remember correctly, regardless if it's stage, map or bonus record

**sm_surftimer_discord_announce_style_main_webhook**

**Comment by tslashd** [comment]
@stunslave if everything is okay now, please let @Sarrus1 know so this issue could be closed, thank you

**Comment by stunslave** [comment]
Well nope... 
Style stage records announce to discord.. 
Map / Bonus records for styles don't announce to discord.

**Comment by Sarrus1** [comment]
Is the value of `sm_surftimer_discord_announce_style_main_webhook` in your config valid?

**Comment by stunslave** [comment]
All my webhooks are valid.. 
Map records go to 🌊┃surf-map
Stage records go to 🌊┃surf-stage
Bonus records go to 🌊┃surf-bonus
All Style records should go to 🌊┃surf-styles but only the stage times go here - The map/bonus times for styles don't go anywhere.

Tested in low grav and hsw also.

![image](https://user-images.githubusercontent.com/47533535/151109932-e6e12dcc-27b8-403b-bfc8-c933a99c04fd.png)
The record should have been between these 2 stage records.
![image](https://user-images.githubusercontent.com/47533535/151109774-e82ed7ec-e307-4538-9332-62880ccae7eb.png)

**Comment by tslashd** [comment]
**Map** and **Bonus** styled messages are indeed not working

**_Styled Stage + Map recs_**
In-game:
![image](https://user-images.githubusercontent.com/74899888/151327424-ed6253e2-b000-4352-8542-46c036c671d1.png)

Discord (other 2 stages are up there as well):
![image](https://user-images.githubusercontent.com/74899888/151327700-7b526c07-2206-4531-91bc-ef8b82c41a43.png)

**_Normal Stage + Map recs_**
In-game:
![image](https://user-images.githubusercontent.com/74899888/151327862-52629a1e-50d8-4fbf-8c5f-136e10c7f6a9.png)

Discord (other 2 stages are up there as well):
![image](https://user-images.githubusercontent.com/74899888/151327963-4bf33d22-a8d2-406f-9812-d2c12c110b0f.png)
