### ISSUE TITLE
[Bug] Map Record - Title + Images broken

### ISSUE THREAD

**Issue by stunslave** [surftimer/SurfTimer-discord#2]
Version: https://github.com/Sarrus1/SurfTimer-discord/releases/tag/v1.0
Newest Dev Version is even more broken.
Surftimer Version: Realase 3.1.9

![image](https://user-images.githubusercontent.com/47533535/126474553-310dba0f-686e-430d-ab86-52fa3c6e25db.png)
Stage Maps with bonuses - Map Record Name says: "New Bonus Record #0"

![image](https://user-images.githubusercontent.com/47533535/126475933-39344bc1-cd94-41e8-84f8-c63c0bacff4c.png)
Stage Maps without bonuses - Map Record Name says: "New Bonus Record #0"
Stage Maps without bonuses - Show no Image

![image](https://user-images.githubusercontent.com/47533535/126476723-34eff4b3-9920-4401-9abf-33013eb5090b.png)
Linear Maps with bonuses - Map Record Name says: "New Bonus Record #0"
Linear Maps with bonuses - Show no Image

![image](https://user-images.githubusercontent.com/47533535/126477154-5942a6fe-f823-4c6f-84d6-310ac07a3bcb.png)
Linear Maps without bonuses - Map Record Name says: "New Bonus Record #0"
Linear Maps without bonuses - Show no Image

Bonus Title + Images work.

**Comment by stunslave** [comment]
![image](https://user-images.githubusercontent.com/47533535/126689972-902ee4ab-4c3d-4731-8429-e3857130c22a.png)
Also KSF style doesnt show records as styles or bonuses.. Shows all as map record.

**Comment by Kyli3Boi** [comment]
![image](https://user-images.githubusercontent.com/64275139/126760871-1e016d59-1e0d-4705-882d-4770e87258a5.png)

This should be fixed once Just-Sad issue #55 is merged as this is a error on surftimer code not this code

**Comment by stunslave** [comment]
I will test later today or on the weekend and see if it's fixed.

> ![image](https://user-images.githubusercontent.com/47533535/126689972-902ee4ab-4c3d-4731-8429-e3857130c22a.png)
> Also KSF style doesnt show records as styles or bonuses.. Shows all as map record.

And the above KSF Style issue?

**Comment by Sarrus1** [comment]
@stunslave The KSF style is legacy code from the Ace fork of ckSurf, I didn't write it and I don't use it.
So it's not really an issue as the code for bonuses doesn't exist at all.

However, I want to implement it in the next release, do you have an idea for the styling?

Here is what I came up with:

![Example](https://i.ibb.co/41D2V6t/surftimer2.png)

**Comment by Sarrus1** [comment]
Can confirm that with [my PR](https://github.com/qawery-just-sad/Surftimer-Official/pull/57) and the PR 55 which has been merged, the record announce works correctly now:

USE THE LATEST .SMX FROM THE REPO, NOT THE RELEASE

Don't mind the image, there are no images for d2 but the URL was correct if there was.

![Example](https://i.ibb.co/ZRQn8KQ/surftimer.png)

**Comment by stunslave** [comment]
kewl kewl thanks.. 
style it how ever you feel is best.
