### ISSUE TITLE
BW (maybe other styles?) reporting personal bests as server records

### ISSUE THREAD

**Issue by Sayt123** [surftimer/SurfTimer-discord#21]
Tested on release v2.2.0 and v2.4.1. 

Personal bests set in backwards are sent as a server record notification, with the time comparison comparing against your personal best not the record.

![image](https://user-images.githubusercontent.com/25940937/184409607-f429994c-3f44-456f-82dd-98c7291a84be.png)

**Comment by shipyy** [comment]
this issue is not related to this plugin, this comes from surtimer itself , fix was already been PR :)

**Comment by Sayt123** [comment]
My brain smooth. Thank you for pointing that out, my bad!
