### ISSUE TITLE
Bug reporting doesnt work(i have a fix)

### ISSUE THREAD

**Issue by pimpmyname2** [surftimer/SurfTimer-discord#25]
Hello the !bug command doesnt work anymore. I spotted the issue.

GetConVarString(g_cvBotUsername, szBugTrackerName, sizeof g_cvBotUsername);

should be:

GetConVarString(g_cvBotUsername, szBugTrackerName, sizeof szBugTrackerName);

**Comment by tslashd** [comment]
`sizeof(yourVariable)` no?

**Comment by Bara** [comment]
> `sizeof(yourVariable)` no?

Both works

**Comment by Sarrus1** [comment]
What is the name of your webhook?

**Comment by pimpmyname2** [comment]
It's a different name than the one named in the cfg. For some reason the calladmin works just fine, even if i paste the webhook equal to bugreport

**Comment by Sarrus1** [comment]
Does it have "Discord" in it? There seems to be a new restriction regarding that in the Discord API.

**Comment by pimpmyname2** [comment]
It's on default. It suddenly just stopped working(it worked last 9th January) so it might be that

**Comment by Sarrus1** [comment]
Try to give it a generic name like "ReportBot" or something

**Comment by pimpmyname2** [comment]
I will try that out tomorrow, im not at a pc rn :)

**Comment by pimpmyname2** [comment]
The Calladmin webhook name has "sm_surftimer_discord_username" but the bugreport bot didnt have that when it all worked.
Line: https://github.com/surftimer/SurfTimer-discord/blob/4f4965da5a5d18bb4f7dcfed9cba350c67f766d2/scripting/SurfTimer-discord.sp#L322
Line: https://github.com/surftimer/SurfTimer-discord/blob/4f4965da5a5d18bb4f7dcfed9cba350c67f766d2/scripting/SurfTimer-discord.sp#L400
I know both should work, but something must be wrong with the Discord API JSON data. I have attached some images. I really doubt renaming it to ReportBot would fix it tho

![calladmin_text](https://user-images.githubusercontent.com/79339372/214500273-bb28eeed-4110-41e7-85f8-59861fa52ca9.PNG)
![webhook_bugreport](https://user-images.githubusercontent.com/79339372/214500294-ca6708bc-d038-4209-b4ea-52151a911428.PNG)

![bugreport_text](https://user-images.githubusercontent.com/79339372/214500292-d17f08f4-131d-45cf-86bb-5613d052801a.PNG)
![webhook_calladmin](https://user-images.githubusercontent.com/79339372/214500300-149ea2d6-b8b9-4e05-a442-28dc21c84415.PNG)

**Comment by tslashd** [comment]
`sm_surftimer_discord_username` is what @Sarrus1 was asking you if it has "Discord" in it.
Recent update on discord forbids the usage of `Discord` in the name of your bots.

**Comment by pimpmyname2** [comment]
It's named SurfTimer BOT

**Comment by tslashd** [comment]
The following restrictions are additionally enforced for usernames:

1. Usernames cannot contain the following substrings: `@, #, :, ```, discord`
2. Usernames cannot be: `everyone, here`

There are other rules and restrictions not shared here for the sake of spam and abuse mitigation, but the majority of users won't encounter them. It's important to properly handle all error messages returned by Discord when editing or updating names.


Took this from Discord Developer Documentation. I would suggest trying to replicate the exact same API call that your plugin is making along with the same "Name" and everything as if the plugin is sending the call through Postman. That way Discord API will most likely return the error why it's not working

**Comment by Sarrus1** [comment]
Hello @pimpmyname2 
Please try [v2.5.2](https://github.com/surftimer/SurfTimer-discord/releases/tag/v2.5.2).

I haven't managed to test it but if you are correct, this might fix the bug.

**Comment by pimpmyname2** [comment]
Amazing. It works, ill close it 👍
