### ISSUE TITLE
No messages sent

### ISSUE THREAD

**Issue by IG-PhantomX** [surftimer/SurfTimer-discord#28]
Want to preface this that I tested the two different webhooks on https://disforge.com/tool/webhook-tester# to ensure my links work.

In game, when I run the test command, it says in game that everything worked fine (all messages sent), and the server console returns no feedback (I assume that is good).  However, my discord channels are not receiving the messages.  I have also just tried manually testing the features as well.

**Comment by tslashd** [comment]
• **WARNING** Discord no longer allows "everyone" and "here" as webhook names, nor the following substrings: "@", "#", ":", "```", "discord".

Please confirm none of these are present for the `Username` of the bot

**Comment by IG-PhantomX** [comment]
sm_surftimer_discord_username "SurfTimer BOT"

That is my config - is there anywhere else to check?

**Comment by tslashd** [comment]
That should be the only place to edit that. 
Works fine for me out of the box, maybe obfuscate private information (webhooks) from the config file and share it.

**Comment by Sarrus1** [comment]
When installing RIPext, did you install the certificate as well? If you don't this will cause a silent error.

**Comment by IG-PhantomX** [comment]
I did not because I already have a certificate in that folder by the same name, slightly different file size.  I'm quite frankly not sure what it is associated to, but I didn't replace it because of that.  Can you advise if it is likely OK to replace it?

**Comment by IG-PhantomX** [comment]
Yes that is correct, the certificate is in the correct directory.

**Comment by Sarrus1** [comment]
Are you able to recompile the plugin in debug mode?
All you have to do is clone the repo and change the `g_bDebugging` variable to true:
https://github.com/surftimer/SurfTimer-discord/blob/master/scripting/SurfTimer-discord.sp#L61

Otherwise I will add a command tonight to toggle debug mode from the game.

**Comment by IG-PhantomX** [comment]
I compiled it in debug mode:

It returned this multiple times:

Processed client n°1's webhook, status 404
An error has occured while sending the webhook.

**Comment by Sarrus1** [comment]
Your webhook link is invalid it seems.
Can you send it here by obfuscating the digits inside it?
I think you have a `/` in there that shouldn't be there.

**Comment by IG-PhantomX** [comment]
I compiled it in debug mode:

It returned this multiple times using the test command:

Processed client n°1's webhook, status 404
An error has occured while sending the webhook.

I tried to doing !report and it generates this:

src/common/httpclient.cpp (808) : pHost && *pHost
L 03/15/2023 - 05:07:44: [discord_api.smx] [DISCORD] Couldn't Send Webhook - Fail 0 0

Here is one of two of my webhook links (obfuscated):

https://discord.com/api/webhooks/5743865464561070233/wHhdokixGU8kKPwgiaABCDA0_oORQnlEFGT2ADe5geYU36uHwp5ngdDpmtcopW9VU8

As stated earlier, I tested both of my links (I used older and brand new links in both cases) before attempting to use the plugin.

**Comment by IG-PhantomX** [comment]
Attached is my debug cfg
[SurfTimer-Discord-debug.txt](https://github.com/surftimer/SurfTimer-discord/files/10981890/SurfTimer-Discord-debug.txt)

**Comment by Sarrus1** [comment]
Ok so in the latest changes, I've added a define called #DEBUG that enables debugging for the webhook itself.
Simply add `#define DEBUG` at the top of the file and recompile it with all the latest changes (especially DiscordWebhookAPI.inc).
Running the tests again will print the whole JSON of the webhook to the server's console.
We will see if it is valid (you might have an invalid URL somewhere).
If it is invalid, then the problem is on our side.
If it is not, you have a problem with your installation.

**Comment by IG-PhantomX** [comment]
Compiled that and here is the return...

L 03/16/2023 - 12:17:09: [SM] Exception reported: Handle b0a002ee is invalid (error 3)
L 03/16/2023 - 12:17:09: [SM] Blaming: SurfTimer-discord.smx
L 03/16/2023 - 12:17:09: [SM] Call stack trace:
L 03/16/2023 - 12:17:09: [SM] [0] CloseHandle
L 03/16/2023 - 12:17:09: [SM] [1] Line 993, ...\COMPILER\scripting\include\discordWebhookAPI.inc::Webhook.Execute
L 03/16/2023 - 12:17:09: [SM] [2] Line 586, ...\COMPILER\scripting\SurfTimer-discord.sp::mapchallenge_OnNewChallenge
L 03/16/2023 - 12:17:09: [SM] [3] Line 224, ...\COMPILER\scripting\SurfTimer-discord.sp::CommandDiscordTest
Processed client n°1's webhook, status 404
An error has occured while sending the webhook.

**Comment by IG-PhantomX** [comment]
Cannot remember how, but it works now.
