### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by stunslave** [surftimer/SurfTimer-discord#30]
```
[SM] Call stack trace:
[SM]   [0] CloseHandle
[SM]   [1] Line 993, C:\Desktop\Server\Files\addons\sourcemod\scripting\include\discordWebhookAPI.inc::Webhook.Execute
[SM]   [2] Line 860, C:\Desktop\Server\Files\addons\sourcemod\scripting\SurfTimer-discord.sp::sendDiscordAnnouncement
[SM]   [3] Line 957, C:\Desktop\Server\Files\addons\sourcemod\scripting\SurfTimer-discord.sp::OnResponseReceived
```
Keeps spamming the logs after a Record is broken, doesn't effect anything other than it just being very annoying.

**Comment by Sarrus1** [comment]
Can you show the whole error please? Not just the stacktrace?

Also try the latest release, I think this has been fixed.

**Comment by tslashd** [comment]
Update the [DiscordWebhookAPI](https://github.com/Sarrus1/DiscordWebhookAPI) include and recompile with it to fix this issue

**Comment by Sarrus1** [comment]
You can use v2.5.8 which should fix the issue 👍
