### ISSUE TITLE
[Question] Any way to announce to two different servers?

### ISSUE THREAD

**Issue by rcnoob** [surftimer/SurfTimer-discord#34]
Title

**Comment by Sarrus1** [comment]
Not without modifying the plugin, no.

Either modify the plugin (just duplicate the `sendAnnouncement` call with a different webhook in each case).

Or create a simple proxy (Python, Rust, Go, whatever) and relay the payload from the plugin to the two webhooks.

One of the solution might be easier than the other depending on your knowledge and system setup.

**Comment by rcnoob** [comment]
https://pastebin.com/raw/jFwAereA

I added cvar webhook1 and function sendDiscordAnnouncement1. It works, but for some reason it sends duplicates to webhook1 server
