### ISSUE TITLE
[IMPROVEMENT] Discord Mentions

### ISSUE THREAD

**Issue by tslashd** [surftimer/SurfTimer-discord#7]
When using the mention cvars, you'd need the correct syntax which is not really mentioned anywhere.

_**@here**_ - will work out of the box
_**@Staff**_ - will **not** work
_**@ROLE_ID**_ - will **not** work
_**<@&role_id>**_  - will work as expected

Thank you @Sarrus1 for the help! :-)

**Comment by Sarrus1** [comment]
Fixed in 1636f99cebb4090d40fc3634f588ee8cc47287ae.
