### ISSUE TITLE
[FEATURE] Styles

### ISSUE THREAD

**Issue by tslashd** [surftimer/SurfTimer-discord#8]
It would be great if we have the option to switch off styled records being sent to discord, or at least change the webhook for styled finishes only. (like we have for map and bonus completions)

Also is there a limit size wise for the images that get shown on DC messages or any other limit? Some maps do not have a picture in the discord message but image exists with the same name and in the same folder that's been set for the plugin to look through

**Comment by charles-zablit** [comment]
> It would be great if we have the option to switch off styled records being sent to discord, or at least change the webhook for styled finishes only. (like we have for map and bonus completions)

Good idea, I will add that on top of disabling `!calladmin` 👍

> Also is there a limit size wise for the images that get shown on DC messages or any other limit? Some maps do not have a picture in the discord message but image exists with the same name and in the same folder that's been set for the plugin to look through

I don't there is, however, it seems like a random `_` is being appended to the map name sometimes whichesses things up. I will work on that 👍

**Comment by Sarrus1** [comment]
> It would be great if we have the option to switch off styled records being sent to discord, or at least change the webhook for styled finishes only. (like we have for map and bonus completions)

Good idea, I will add that on top of disabling `!calladmin` 👍

> Also is there a limit size wise for the images that get shown on DC messages or any other limit? Some maps do not have a picture in the discord message but image exists with the same name and in the same folder that's been set for the plugin to look through

I don't there is, however, it seems like a random `_` is being appended to the map name sometimes whichesses things up. I will work on that 👍
